# Generated by Django 3.2.8 on 2021-12-23 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20211223_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='customerID',
        ),
        migrations.RemoveField(
            model_name='order_product',
            name='productCode',
        ),
    ]
